version: '2'
services: 
  web:
    build: .
    ports:
      - "80:5000"
    volumes:
      - /Flask/petsapi:/Flask/petsapi
    links:
     - db:mongodb
    container_name: petapi_web_1
    depends_on:
      - db
  db:
    image: mongo:3.0.2
    container_name: petsapi_db_1